refactor: update linting
ref: https://github.com/nofusscomputing/centurion_erp/issues/1096

diff --git a/.github/workflows/reusable_mkdocs.yaml b/.github/workflows/reusable_mkdocs.yaml
--- a/.github/workflows/reusable_mkdocs.yaml
+++ b/.github/workflows/reusable_mkdocs.yaml
@@ -19,7 +19,7 @@ jobs:
   lint:
     name: 'Lint'
     env:
-      MDLINT_PATHS: '"docs/*.md docs/**/*.md docs/**/**/*.md docs/**/**/**/*.md docs/**/**/**/**/**/*.md #CHANGELOG.md !gitlab-ci !website-template"'
+      MDLINT_PATHS: '"docs/*.md docs/**/*.md docs/**/**/*.md docs/**/**/**/*.md docs/**/**/**/**/**/*.md #CHANGELOG.md"'
     runs-on: ubuntu-latest
     steps:
 
@@ -28,28 +28,18 @@ jobs:
         uses: actions/checkout@v4
 
 
-      - name: Init Git Submodules
-        shell: bash
-        run: |
-          git submodule update --init;
-          git submodule foreach git submodule update --init;
-
-          ls -ls
-
-
       - name: Install Dependencies
         shell: bash
         run: |
           sudo apt update;
           sudo apt install -y --no-install-recommends npm;
 
-
       - name: Install Linter
         shell: bash
         run: |
-          npm install markdownlint-cli2@v0.18.1 --global
-          npm install markdownlint-cli2-formatter-junit --global       
-
+          npm install markdownlint-cli2@v0.18.1 --global;
+          npm install markdownlint-cli2-formatter-junit --global;
+          npm install markdownlint-cli2-formatter-template --global;
 
       - name: Create Artifact directory
         shell: bash
@@ -57,26 +47,11 @@ jobs:
           mkdir -p artifacts
 
 
-      - name: Add linting rules
+      - name: Enable Problem Matcher
         shell: bash
         run: |
-          if [ ! -f ".markdownlint.json" ]; then
-
-            ls -la website-template;
-
-            cp "website-template/.markdownlint.json" ".markdownlint.json";
-
-          fi;
-
-          if [ ! -f ".markdownlint-cli2.jsonc" ]; then
-
-            ls -la gitlab-ci/lint
-
-            cp -f "gitlab-ci/lint/.markdownlint-cli2.jsonc" ".markdownlint-cli2.jsonc";
-
-          fi
-
-          ls -la;
+          echo "NFC_PROBLEM_MATCHER=${GITHUB_REF_NAME}";
+          echo "NFC_PROBLEM_MATCHER_TYPE=markdown-lint";
 
 
       - name: Lint
@@ -101,7 +76,6 @@ jobs:
           
           mv -vf markdown.junit.xml "artifacts/markdown_lint.junit.xml"
 
-
       - name: debug ls
         if: ${{ success() || failure() }}
         shell: bash
@@ -109,17 +83,20 @@ jobs:
           ls -la artifacts/;
 
 
-
       - name: Check if Linting Error Occured
         shell: bash
         run: |
-          if [ ${{ steps.lint.outputs.exit_code }} -ge 3 ]; then
+          if [ "0${{ inputs.ANSIBLE_LINTING_MUST_PASS }}" == "0true" ]; then
 
-            echo "[Error] ansible lint failed with  ${{ steps.lint.outputs.exit_code }}";
-            
-            exit ${{ steps.lint.outputs.exit_code }};
+            if [ ${{ steps.lint.outputs.exit_code }} -ge 3 ]; then
 
-          fi # don't fail the job?? 1=failed test, 2=failed command i.e. switch/flag
+              echo "[Error] ansible lint failed with  ${{ steps.lint.outputs.exit_code }}";
+              
+              exit ${{ steps.lint.outputs.exit_code }};
+
+            fi # don't fail the job?? 1=failed test, 2=failed command i.e. switch/flag
+
+          fi
 
 
       - name: Upload build Artifact
@@ -128,24 +105,6 @@ jobs:
         with:
           name: mkdocs-lint
           path: artifacts/
-
-
-      - name: Should the Job be force failed?
-        shell: bash
-        run: |
-          if [ "0${{ inputs.ANSIBLE_LINTING_MUST_PASS }}" == "0true" ]; then
-
-            if [ ${{ steps.lint.outputs.exit_code }} -gt 0 ]; then
-
-              echo "[Trace] ANSIBLE_LINTING_MUST_PASS[${{ inputs.ANSIBLE_LINTING_MUST_PASS }}]";
-              
-              echo "[Error] ansible lint failed with ${{ steps.lint.outputs.exit_code }}";
-            
-              exit ${{ steps.lint.outputs.exit_code }};
-          
-            fi
-
-          fi
 
 
 
